version: "3.9"
networks:
  mynet:
    driver: bridge
volumes:
  mysql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mysql
  rabbitmq:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/rabbitmq
  redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/redis
  mongodb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mongodb
services:
  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - mysql
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  ratings:
    image: ratings:v1
    container_name: ratings
    depends_on:
    - mysql
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
